POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Melvin",
    "lastName": "Joseph",
    "email": "josmeleph@gmail.com",
    "password": "@Kassword123",
    "isAuth": true 
}